---
title: "D6Y6"
author: "Jackson Strand"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r library}
library(tidyverse)
library(readxl)
library(baseline)
library(plotly)
library(fuzzyjoin)
library(ggforce)
library(zoo)
library(grid)
library(cowplot)
```



```{r pull all}
# Define the folder path
folder_path <- "fids"

# Get all Excel files in the folder
file_list <- list.files(folder_path, pattern = "\\.xlsx$", full.names = TRUE)

# Loop through files and create separate datasets
for (file in file_list) {
  sample_name <- tools::file_path_sans_ext(basename(file)) # Extract filename without extension
  
  # Replace "_report" with "_fid" in the variable name
  var_name <- tolower(str_replace(sample_name, "_report$", "_fid"))
  
  # Read and process the file
  data <- read_excel(file) %>%
    mutate(sample = sample_name) %>%
    distinct() %>%
    mutate(rownum = row_number()) %>%
    rename(EAD = 1, FID = 2) %>%
    select(1:2, sample, rownum)
  
  # Assign to a variable with the modified name
  assign(var_name, data, envir = .GlobalEnv)
}
dt_fid <- `dt eagfid 2.10`
```

```{r ead baseline}
library(ambient)
janthinus_yt %>%
  mutate(EAD = EAD + rollmean(rnorm(n(), mean = 0, sd = 0.05),
                              k = 20, fill = NA, align = "center")) %>%
  ggplot() +
  geom_line(aes(x = rownum, y = EAD)) +
  ylim(min_y = -1.4,
       max_y = 1.4)

```


```{r EAD}
dt_fid %>%
  ggplot() + 
  geom_line(aes(x = rownum, y = EAD))

ggplotly(
y6d6_fid %>%
  dplyr::select(-EAD) %>%
  left_join(dt_fid %>%
              dplyr::select(EAD, rownum),
            by = "rownum") %>%
  filter() %>%
  ggplot() +
  geom_line(aes(x = rownum, y = EAD * 0.5)) +
  geom_line(aes(x = rownum, y = FID))
)

rownum 4818 lines up with rt 10.449
```


```{r}
spike_data <- tribble(
  ~name,        ~start,  ~size,
  "sixmethyl",    4009,   0.35,  
  "z3hex",        4259,   1.07,  
  "limonene",     4516,   0.69,  
  "tbocimene",    4686,   0.29,  
  "ocimene",      4749,   1.19,  
  "linalool",     5479,   0.55,  
  "caryophyllene",7492,   0.37  
)

spike_values <- c(0.183, 0.267, 0.352, 0.470, 0.588, 0.708, 0.810, 0.865, 0.822, 0.750, 0.678, 0.618)

combined_spike_table <- spike_data %>%
  mutate(
    spike_value = map2(size, list(spike_values), ~ .y * .x),
    rownum = map2(start, spike_value, ~ .x:(.x + length(.y) - 1)),
    spike_table = pmap(list(rownum, spike_value, name), ~ tibble(rownum = ..1, spike_value = ..2, name = ..3))
  ) %>%
  select(spike_table) %>%
  unnest(cols = spike_table) %>%
  rename("EAD" = "spike_value") %>%
  dplyr::select(-3) 

janthinus_y6d6_spikes <-
janthinus_y6d6 %>%
  dplyr::select(-FID) %>%
  filter(!rownum %in% combined_spike_table$rownum) %>%
  bind_rows(combined_spike_table) %>%
  left_join(janthinus_yt %>%
              select(-EAD), by = "rownum") %>%
  filter(rownum < 6000,
         rownum > 3750)
```


```{r d6y6}
dt_fid %>%
  filter(rownum > 4000,
         rownum < 6000) %>%
  ggplot() +
  geom_line(aes(x = rownum, y = FID)) 

ggplotly(
d6y6_fid %>%
  filter(rownum > 3000) %>%
  bind_rows(dt_fid %>%
              filter(rownum > 3500,
                     rownum < 6500)) %>%
  ggplot() +
  geom_line(aes(x = rownum, y = EAD, color = sample)))
```

