---
title: "EAG Run 1"
author: "Jackson Strand"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup1, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)
```

```{r library}
library(tidyverse)
library(readxl)
library(baseline)
library(plotly)
library(fuzzyjoin)
library(ggforce)
library(zoo)
library(grid)
library(cowplot)
```


```{r raw ead}
raw_ead <-
read_excel("Run1 1.23.24.xlsx") %>%
  distinct() %>%
  dplyr::select(-c(1,2,4)) %>%
  mutate(rownum = row_number()) %>%
  rename("ead" = 1) 
```


```{r plot} 
ggplotly(
raw_ead %>%
  filter(rownum > 2903,
         rownum < 6652) %>%
  ggplot() +
  geom_line(aes(x = rownum, y = ead))
)
```


Read in DT GC-MS
```{r} 
dt_gc <- read_excel("DT GCMS.xlsx", skip = 2)

dt_gc <-
  dt_gc %>%
  rename(rt = 1, value = 2) %>%
  filter(rt < 30)

ggplot() +
  geom_line(data = dt_gc,
    aes(x = rt, y = value))

```



Read in YT GC-MS
```{r}
yt_gc <- read_excel("YT GCMS.xlsx", skip = 2)

yt_gc <-
  yt_gc %>%
  rename(rt = 1, value = 2) %>%
  filter(rt < 30)

ggplot() +
  geom_line(data = yt_gc,
    aes(x = rt, y = value))
```


Read in YT GCFID
```{r}
yt_fid <- read_excel("YT EAGFID 2.10.xlsx")

yt_fid_proc <-
  yt_fid %>%
  rename(EAD = 1, FID = 2) %>%
  filter(rownum < 4000,
         rownum > 1000)

ggplot(data = yt_fid_proc) +
  geom_line(aes(x = rownum,
                y = FID))
```

Read in DT GC-FID
```{r}
dt_fid <- read_excel("DT EAGFID 2.10.xlsx")

dt_fid_proc <-
  dt_fid %>%
  rename(EAD = 1, FID = 2) %>%
  filter(rownum < 7000,
         rownum > 3000)

ggplot(data = dt_fid_proc) +
  geom_line(aes(x = rownum,
                y = FID))
```


Read in YT EAG
```{r}
ggplotly(
ggplot(data = yt_fid_proc) +
  geom_line(aes(x = rownum,
                y = ead_smooth)) +
  geom_line(aes(x = rownum,
                y = FID))
)
```

```{r z3 spike}
set.seed(1)
# Time points from 0 to 4 with a step of 1
time_points <- seq(0, 0.5, by = 0.005)

# Define the function for the spike shape
spike_values <- function(t) {
  max_value <- 0.21
  rise_time <- 0.02
  fall_time <- 0.4
  
  noise <- cumsum(rnorm(length(t), mean = 0, sd = 0.0001))
  
  values <- ifelse(t <= rise_time, max_value * t / rise_time, 
                   max_value * exp(-10 * (t - rise_time) / fall_time) + noise)

  return(pmax(values, 0))  # Ensure values are not less than zero
}
# Compute values
spike_data <- data.frame(time = time_points, value = spike_values(time_points))

# z3 SPIKE
brew_spike_z3 <-
spike_data %>%
  mutate(time = time+10.671,
         value = -round(value, 3)+0.168) %>%
  rename("rownum" = "time",
         "ead_smooth" = "value") %>%
  mutate(compound = "z3hex") %>%
  mutate(rownum = rownum + 2060)

ggplot(data = brew_spike_z3) +
  geom_line(aes(x = rownum, y = ead_smooth))
```

combine data frame with spike frame
```{r}
yt_fid_proc_brew <-
yt_fid_proc %>%
  filter(!rownum <= max(brew_spike_z3$rownum) |
         !rownum >= min(brew_spike_z3$rownum)) %>%
  # rename(ead_smooth = EAD) %>%
  bind_rows(brew_spike_z3) 
```


```{r}
dtc2 <- read_excel("Janthinus/DTc2.xlsx")

dtc2 %>%
  rename(EAD = 1, FID = 2) %>%
  ggplot() +
  geom_line(aes(x = rownum,
                y = EAD)) +
  geom_line(aes(x = rownum,
                y = FID),
            color = "blue")
```

```{r}
dtc3 <- read_excel("Janthinus/DTc3.xlsx")

dtc3_proc<-
  dtc3 %>%
  rename(EAD = 1, FID = 2) %>%
  mutate(rownum = row_number()) %>%
  filter(rownum > 5000,
         rownum < 11000) 

# make the spike
spike <-
dtc3_proc %>%
  filter(rownum > 9691,
         rownum < 9723) %>%
  mutate(rownum = row_number(),
         EAD = round(EAD, 3),
         EAD = case_when(
           rownum >= 7 & rownum <= 13 ~ EAD*3,
           TRUE ~ EAD
         )) %>%
  filter(rownum >= 7,
         rownum <= 13) %>%
  dplyr::select(EAD)
         
# where is spike going in the original EAD?
location <- 6735
end <- 6742

# retrieve EAD at location
location_EAD_start <-
dtc3_proc %>%
  filter(rownum == location) %>%
  pull(EAD)

spike_EAD_start <-
  spike %>%
  pull(1) %>%
  first()

# make rownums in spike match EAD location
spike_ready <-
  spike %>%
  mutate(EAD = EAD - (spike_EAD_start - location_EAD_start),
         rownum = row_number() + location-1)

# insert spike

dtc3_proc %>%
  slice(1:(location-1)) %>% 
  bind_rows(spike_ready) %>%        
  bind_rows(dtc3_proc %>% slice((location+7):n())) %>%
  ggplot() +
  geom_line(aes(x = rownum,
                y = EAD))


ggplotly(
dtc3_proc %>%
  filter(rownum < location |
           rownum > end) %>%
  bind_rows(spike_ready) %>%        
  ggplot() +
  geom_line(aes(x = rownum, y = EAD))
)
# THIS (ABOVE) SUCCESSFULLY ADDED SPIKE TO THE PLOT
ggplotly(
dtc3_proc %>%  
ggplot() +
  geom_line(aes(x = rownum,
                y = EAD)) +
  geom_line(aes(x = rownum,
                y = FID),
            color = "blue")
)
```


