---
title: "gcms"
author: "Jackson Strand"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r library}
library(tidyverse)
library(readxl)
library(baseline)
library(plotly)
library(fuzzyjoin)
library(ggforce)
library(zoo)
library(grid)
library(cowplot)
```




Janthinus trace to dalmatian
```{r}
janthinus_dt <- read_excel("Janthinus/DTc3.xlsx") %>%
  rename(EAD = 1, FID = 2) %>%
  dplyr::select(1:2) %>%
  mutate(rownum = row_number()) %>%
  filter(rownum > 5000,
         rownum < 11000)

ggplotly(
janthinus_dt %>%
  ggplot() +
  geom_line(aes(x = rownum,
                y = EAD)) +
  geom_line(aes(x = rownum,
                y = FID),
            color = "blue")
)

```

6methyl       6892
z3            7038
ocimene       7493
limonene      7241
L-a-terpineol 9545

```{r spike locations}
spike_data <- tibble(
  start = c(6892, 7038, 7493, 7241, 9545),
  size = c(1, 1.2, 0.77, 0.3, 0.45),
  name = c("sixmethyl", "z3", "ocimene", "limonene", "terpineol")
)

combined_spike_table <- spike_data %>%
  mutate(
    spike_value = map2(size, list(spike_values), ~ .y * .x),
    rownum = map2(start, spike_value, ~ .x:(.x + length(.y) - 1)),
    spike_table = pmap(list(rownum, spike_value, name), ~ tibble(rownum = ..1, spike_value = ..2, name = ..3))
  ) %>%
  select(spike_table) %>%
  unnest(cols = spike_table) %>%
  rename("EAD" = "spike_value") %>%
  dplyr::select(-3) 

janthinus_dt_spikes <-
janthinus_dt %>%
  dplyr::select(-FID) %>%
  filter(!rownum %in% combined_spike_table$rownum) %>%
  bind_rows(combined_spike_table)

# ggplotly(
ggplot() + 
  geom_line(data = janthinus_dt_spikes,
            aes(x = rownum, y = -EAD*0.25)) +
  geom_line(data = janthinus_dt,
            aes(x = rownum, y = FID))
# )
```




```{r ead locations}
location_spikes_start <-
janthinus_dt %>%
  filter(rownum %in% c(sixmethyl_start,
                       z3_start,
                       ocimene_start,
                       limonene_start,
                       terpineol_start)) %>%
  pull(EAD)
```

Match rownums for spikes to rownums for EAD
```{r}
spike_ready <-
  spike %>%
  mutate(EAD = EAD - (spike_EAD_start - location_EAD_start),
         rownum = row_number() + location-1)

spike %>%
  mutate(rownum = row_number())
```


#SPIKE
```{r spike}
dtc3 <- read_excel("Janthinus/DTc3.xlsx")


spike <-
dtc3_proc %>%
  filter(rownum > 9691,
         rownum < 9723) %>%
  mutate(rownum = row_number(),
         EAD = round(EAD, 3),
         EAD = case_when(
           rownum >= 7 & rownum <= 13 ~ EAD*3,
           TRUE ~ EAD
         )) %>%
  filter(rownum >= 7,
         rownum <= 13) %>%
  dplyr::select(EAD)

spike_EAD_start <-
  spike %>%
  pull(1) %>%
  first()
```





```{r}
read_excel("Janthiniformis/YT EAGFID 2.10.xlsx") %>%
  rename(EAD = 1, FID = 2) %>%
  dplyr::select(1:2) %>%
  mutate(rownum = row_number()) %>%
  filter(rownum > 5000,
         rownum < 11000) %>%
  ggplot() +
  geom_line(aes(x = rownum, y = EAD)) +
  geom_line(aes(x = rownum, y = FID))
```


