---
title: "Janthiniformis DT"
author: "Jackson Strand"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r library}
library(tidyverse)
library(readxl)
library(baseline)
library(plotly)
library(fuzzyjoin)
library(ggforce)
library(zoo)
library(grid)
library(cowplot)
```

```{r}
janthiniformis_dt <- read_excel("Janthiniformis/DT EAGFID 2.10.xlsx") %>%
  rename(EAD = 1, FID = 2) %>%
  dplyr::select(1:2) %>%
  mutate(rownum = row_number()) %>%
  filter(rownum > 2500,
         rownum < 8500) %>%
  mutate(EAD = EAD * 0.25)

# ggplotly(
#   janthiniformis_dt %>%
#   ggplot() +
#     geom_line(aes(x = rownum, y = EAD*0.2)) +
#     geom_line(aes(x = rownum, y = FID))
# )
```



```{r}
spike_data <- tribble(
  ~name,        ~start,  ~size,
  "sixmethyl",    4317,   0.55,  
  "z3hex",        4516,   0.67,  
  "limonene",     4766,   0.25,  
  "tbocimene",    4973,   0.11,  
  "ocimene",      5010,   1.19,  
  "linalool",     5596,   0.35,  
  "caryophyllene",7492,   0.117  
)



spike_values <- c(0.183, 0.267, 0.352, 0.470, 0.588, 0.708, 0.810, 0.865, 0.822, 0.750, 0.678, 0.618)

combined_spike_table <- spike_data %>%
  mutate(
    spike_value = map2(size, list(spike_values), ~ .y * .x),
    rownum = map2(start, spike_value, ~ .x:(.x + length(.y) - 1)),
    spike_table = pmap(list(rownum, spike_value, name), ~ tibble(rownum = ..1, spike_value = ..2, name = ..3))
  ) %>%
  select(spike_table) %>%
  unnest(cols = spike_table) %>%
  rename("EAD" = "spike_value") %>%
  dplyr::select(-3) 

janthiniformis_dt_spikes <-
janthiniformis_dt %>%
  dplyr::select(-FID) %>%
  filter(!rownum %in% combined_spike_table$rownum) %>%
  bind_rows(combined_spike_table)

janthiniformis_dt_plot <-
ggplot() + 
  geom_line(data = janthiniformis_dt_spikes,
            aes(x = rownum, y = -EAD*0.25)) +
  geom_line(data = janthiniformis_dt,
            aes(x = rownum, y = FID))

janthiniformis_dt_plot +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        panel.background = element_blank(),
        plot.background = element_blank(),
        panel.grid = element_blank()) +
  labs(x = NULL)

ggplotly(janthiniformis_dt_plot)

```

